# permissions for end users to view pulsarconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarconsumer-viewer-role
rules:
- apiGroups:
  - pulsar.pulsarconsumer.krvarma.com
  resources:
  - pulsarconsumers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pulsar.pulsarconsumer.krvarma.com
  resources:
  - pulsarconsumers/status
  verbs:
  - get
